### ISSUE TITLE
Preload more stuff

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/realworld#1]
Loading articles once you've already navigated to the page feels bad. It should be done in `preload`. That way we can also prefetch on hover, etc

**Comment by QuantumInformation** [comment]
I'll take a look at this soon.

**Comment by QuantumInformation** [comment]
How do you want to preload per user, latest 20 posts from followed users?

**Comment by matthiasprieth** [comment]
@QuantumInformation Yeah that would be cool, cause Prefetching/Server Side Rendering is the stuff which is new for me & what I wanted to check out in a "real world example". 

Thought the list of feeds (latest posts) would be rendered in the first html & the rest would be rehydrated.

So at the moment I'm deciding between nextjs & sveltejs/sapper, but SSR seems to be more complicated then I thought it will be.

**Comment by QuantumInformation** [comment]
why not just a SPA?, check out https://svelte-fullstack-starter.firebaseapp.com/

**Comment by benmccann** [comment]
This is done at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev
