### ISSUE TITLE
Cannot start on localhost

### ISSUE THREAD

**Issue by unolife** [sveltejs/realworld#107]
I typed "npm install" first, then "npm run dev" but It occurs an error. Does anyone can help to fix it? I'm new to learning Svelte.

> svelte-kit dev

(node:10381) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/username/realworld/node_modules/@sveltejs/kit/dist/cli.js:1176
					} else if (allow?.length && cwd) {
					                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)

**Comment by benmccann** [comment]
You probably are using an old version of Node JS. Please make sure you're using 14+

**Comment by Conduitry** [comment]
Maybe we should make sure that all our projects have an .npmrc enabling engine-strict (like new projects from the template already do) so this is more obvious.

**Comment by benmccann** [comment]
done
