### ISSUE TITLE
bug: trying to call a `json` variable that is a string — instead of a function

### ISSUE THREAD

**Issue by diegonyc** [sveltejs/realworld#124]
# Context

In the following [file on line 11](https://github.com/sveltejs/realworld/blob/796b8a3ac9a25ff37398a616d778812bc32862f1/src/routes/auth/_respond.js#L11) you have a `return json( ...` statement.

However, `json` is in the local scope of the function and it's a string. Did you mean to import the `json` function from `@sveltejs/kit`?

**Comment by benmccann** [comment]
thank you. fixed here: https://github.com/sveltejs/realworld/commit/26d44c943b43d7e72e4e9ed786268a72f157f8cd
