### ISSUE TITLE
How to handle hooks without session (latest SvelteKit update)

### ISSUE THREAD

**Issue by yadoga** [sveltejs/realworld#125]
Wondering how hooks / locals are going to work after Sessions are now removed?

https://github.com/sveltejs/kit/discussions/5883

**Comment by Conduitry** [comment]
`locals` work the same way as they did before `session` was removed.

GitHub issues aren't the right place for questions like this, especially not on a repo for an example project.

**Comment by benmccann** [comment]
I'll update this app before long to update to the latest and remove session so you can have an example. It's high on my to-do list, but squeezed in with a number of other things
