### ISSUE TITLE
How to use/store Access and Refresh Token following this app and sveltekit

### ISSUE THREAD

**Issue by souravjamwal77** [sveltejs/realworld#127]
I have a Django backend and I'm using DRF (Django Rest Framework) along with simple-jwt for jwt tokens. I'm getting access and refresh tokes from the backend, but I don't know how to set them properly in the sveltekit. I'm following this repo's example but it seems like a hash of the access and the refresh tokens are being saved on the server side.

also, I need SSR so shall store a hash of refresh tokens in cookies and access token in localStorage?
Where shall I store access and refresh tokens? (in localStorage or cookies),

**Comment by benmccann** [comment]
this type of question is better suited towards another forum like Discord, StackOverflow, or GitHub discussions. the issue tracker is really only meant for bug reports
