### ISSUE TITLE
missing profile variable declaration

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/realworld#131]
In the following file https://github.com/sveltejs/realworld/blob/02d0a0713aa6de94f4fef1634e96e8dd7633eb4e/src/routes/profile/%2540%5Buser%5D/%2Blayout.svelte#L20, a variable profile is assigned a value but I can't find where the variable is declared.

Is this some kind of global variable?

**Comment by wvhulle** [comment]
In the file https://github.com/sveltejs/realworld/blob/master/src/routes/profile/%2540%5Buser%5D/%2Blayout.js profile is returned but it is not referenced through the data prop. How is this possible?

**Comment by benmccann** [comment]
Yeah, looks like that will need to be fixed. For reference, here is was before the migration: https://github.com/sveltejs/realworld/blob/e8edaded1dc65c2e062d1ba374560c3bd23b6756/src/routes/profile/%2540%5Buser%5D/__layout.svelte

**Comment by Juri-Salminen** [comment]
"profile" is a property of the "data"-object returned by the load()-function in +page.js, hence "profile" should be referenced as "data.profile" instead of just "profile".
See #132

**Comment by benmccann** [comment]
Fixed here: https://github.com/sveltejs/realworld/commit/f73bd9405cbca7563a6f0fff3eadce9174a20eb9. It looks like the toggling needed a fix on the server-side as well
