### ISSUE TITLE
Missing Editor and Profile routes?

### ISSUE THREAD

**Issue by rzvdaniel** [sveltejs/realworld#14]
**Update:**
I think matt3224 has a pull request that will fix some of the issues described below.

Hi,

When trying the Demo at https://svelte-realworld.now.sh I noticed that the Editor is not working.

The route is: https://svelte-realworld.now.sh/editor

Same happens when navigating to profile:
https://svelte-realworld.now.sh/@Razvan%20Predescu

Here is a screenshot:

![editor](https://user-images.githubusercontent.com/1128179/53429735-1ab6ea80-39e5-11e9-949d-6ff6f836e4af.PNG)

Best!
Razvan

**Comment by QuantumInformation** [comment]
Still has same issue

https://svelte-realworld.now.sh/@wefw

**Comment by pngwn** [comment]
Fixed in #16.

**Comment by nickolasgregory** [comment]
Fix in the repo, but [svelte-realworld.now.sh](https://svelte-realworld.now.sh) needs updating.
