### ISSUE TITLE
Profile endpoint throwing error

### ISSUE THREAD

**Issue by joci-tildeloop** [sveltejs/realworld#144]
[Endpoint](https://realworld.svelte.dev/profile/@Magda%20Parry) is broken, doesn't show profile as the stock Real World app does.

Initial progress bar stuck at 10% with an empty main tag. After the refresh throws a HTTP 500 error.

**Comment by benmccann** [comment]
fixed here: https://github.com/sveltejs/realworld/commit/97ea90229c55bef531cc3b21506f4a2c7ad6e649
