### ISSUE TITLE
Pages do not change

### ISSUE THREAD

**Issue by shinokada** [sveltejs/realworld#145]
On my local host, when I click login, register etc, the url changes but content doesn't.

**Comment by vi66ko** [comment]
The links of the navigation work fine on my localhost.
? Is there any error in:
- the console, 
- the terminal
- Network tab in the browser Developer Tools

**Comment by shinokada** [comment]
I get this error in the browser console. No errors on the terminal.
I'm using pnpm.

![image](https://user-images.githubusercontent.com/147320/202838077-de1642d6-7c96-4982-82d0-fd667cdf4365.png)

**Comment by vi66ko** [comment]
Sory I am not familliar with pnpm.

If you haven't done it yet, you can make a fresh download/clone of the master branch.
And if still does not work. 
Why not try using npm?

**Comment by shinokada** [comment]
Ok, I cloned it and use npm and it still doesn't work.
Here are my system info:

```
envinfo --system --npmPackages svelte,@sveltejs/kit,vite,rollup,webpack --binaries --browsers    

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 57.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5426.0
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.551 
    svelte: ^3.52.0 => 3.53.1 
    vite: ^3.2.2 => 3.2.4 
```

**Comment by shinokada** [comment]
I found that it works with Chrome/FF but not with Brave.

**Comment by vi66ko** [comment]
That is strange!
On my brave is working absolutly fine.

![image](https://user-images.githubusercontent.com/9287260/202891048-dec84067-56b4-4e42-9824-15cd7fce0cca.png)


<details>
  <summary>Here you are part of my System: info</summary>
  
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 4.17 GB / 15.78 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Brave: [Version 1.45.127 Chromium: 107.0.5304.110 
    Chrome: 107.0.5304.107
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.544
    svelte: ^3.52.0 => 3.53.1
    vite: ^3.2.2 => 3.2.3
</details>
