### ISSUE TITLE
A working demo with authentication

### ISSUE THREAD

**Issue by shinokada** [sveltejs/realworld#148]
Is it possible to create a working demo like [Next.js realworld](https://next-real-world.vercel.app/). 
They allow us to sign up, login, post, edit etc.
Can you make [Sveltekit realworld](https://realworld.svelte.dev/) demo to have the similar functions?

**Comment by benmccann** [comment]
we already have all these functionalities. for example:
- signup - https://realworld.svelte.dev/register
- login - https://realworld.svelte.dev/login

**Comment by shinokada** [comment]
But they are not working.
I always get:

```
email has already been taken
username has already been taken
```

![image](https://user-images.githubusercontent.com/147320/203444305-a599f6a0-a986-4c4e-b706-e9f20a5e2e47.png)

**Comment by benmccann** [comment]
try a more unique username and email. i'm not surprised "test" has been registered already

**Comment by shinokada** [comment]
Thanks.
