### ISSUE TITLE
Add use of .env files for dev and prod evvironment

### ISSUE THREAD

**Issue by alokmahor** [sveltejs/realworld#160]
In `src/lib/api.js` https://api.realworld.io/api should come from .env file.

**Comment by benmccann** [comment]
Why?

**Comment by benmccann** [comment]
Why? Is there some different URL you would use for development vs production? What is that URL?

**Comment by alokmahor** [comment]
> Why? Is there some different URL you would use for development vs production? What is that URL?

Its a example project. So to show example usage of .env files in sveltekit.

**Comment by benmccann** [comment]
If the URL is going to be the same I'm not sure that's a good example

**Comment by alokmahor** [comment]
> If the URL is going to be the same I'm not sure that's a good example

This is a example project. People are using this project to see way to use sveltekit and its library functions in real word scenario.
