### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by TheBeachMaster** [sveltejs/realworld#180]
Doing anything results into **Something went wrong**

![Screenshot 2024-09-11 at 23 52 45](https://github.com/user-attachments/assets/e15d01e5-8f95-4526-9bb6-83dc90ad6ace)

**Comment by sahilrajput03** [comment]
I am seeing this issue too - 
![image](https://github.com/user-attachments/assets/fd3b4a0f-eab5-437a-9b95-d93102b1edcb)

**Comment by benmccann** [comment]
please see https://github.com/gothinkster/realworld/issues/1611
