### ISSUE TITLE
Error while building with container

### ISSUE THREAD

**Issue by lsabi** [sveltejs/realworld#21]
I'm using buildah and podman which are (in theory) compliant with the docker system.

I run the following two commands for building and running the container from the dockerfile

`buildah bud -t test .`
`podman run -p 3000:3000 test`

and I get
`internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module \'/app/__sapper__/build\'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  code: \'MODULE_NOT_FOUND\',
  requireStack: []
}`

Am I doing something wrong or is there some problem?

Thanks

**Comment by lsabi** [comment]
Solved changing the Dockerfile

`FROM mhart/alpine-node:12
WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
`

This works on my computer. Further checks are needed also with different environments

**Comment by QuantumInformation** [comment]
can you close?
