### ISSUE TITLE
The backend needs to be expecting a token base?

### ISSUE THREAD

**Issue by mylastore** [sveltejs/realworld#22]
Is not authorizing for me, my express backend is set up with session cookie. Or this only works with token base authorization only?

**Comment by QuantumInformation** [comment]
The token is passed as so, you should read the header

https://github.com/sveltejs/realworld/blob/master/src/node_modules/api.js#L13

**Comment by mylastore** [comment]
Cool, Got working with the token now. Thank you so much.

**Comment by QuantumInformation** [comment]
can you close pls?
