### ISSUE TITLE
404 when clicking on a username

### ISSUE THREAD

**Issue by JeffWScott** [sveltejs/realworld#26]
The demo throws a 404 error when clicking on a user's name.  Other implementations go to a user history screen.

**Comment by pngwn** [comment]
The demo is actually the old Svelte 2 version. This issue was corrected in #17 when the project was updated for Svelte 3. Unfortunately, we have been having some deploy issues and the old version keeps sticking around.

**Comment by QuantumInformation** [comment]
What issues? I've been testing extensively locally and its all good.

**Comment by QuantumInformation** [comment]
I'll try deploy it to my google cloud soon and report back

**Comment by pngwn** [comment]
Now we have the correct version deployed, this should no longer be an issue.
