### ISSUE TITLE
[Question] Where is the token?

### ISSUE THREAD

**Issue by Olyno** [sveltejs/realworld#28]
Hi, I have just a question about the source: in the api, we need a token right?
https://github.com/sveltejs/realworld/blob/master/src/node_modules/api.js#L36

And here, there are no one token
https://github.com/sveltejs/realworld/blob/master/src/routes/auth/register.js#L6

So my question is: where is the token and how use it?

**Comment by QuantumInformation** [comment]
The token is saved in the $session. One thing I'm not sure is why it has to be passed to the client given that it is saved in the express-session

**Comment by QuantumInformation** [comment]
This might interest you too

https://github.com/sveltejs/realworld/issues/33

**Comment by QuantumInformation** [comment]
Can we close this?
