### ISSUE TITLE
Write some acceptance tests

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/realworld#4]

**Comment by GeorgeTailorZooPlus** [comment]
what about unit tests ?

**Comment by pngwn** [comment]
Kind of implemented in #16. Do we need more?

**Comment by QuantumInformation** [comment]
Would cypress work?

**Comment by pngwn** [comment]
If you look [here](https://github.com/sveltejs/realworld/tree/master/cypress) you will see that Cypress is already being used for the acceptance tests that we currently have. The reason I left this issue open is that they aren't comprehensive and someone might want to add to them in the future.

**Comment by QuantumInformation** [comment]
Ah ok, is there any persistance / roll back with the backend going on?

**Comment by quantuminformation** [comment]
Any ideas for a mock backend to run e2e against?

**Comment by quantuminformation** [comment]
mirage.js?

**Comment by benmccann** [comment]
A more actively maintained version now lives at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev
