### ISSUE TITLE
New session file on backend with each page refresh

### ISSUE THREAD

**Issue by quantuminformation** [sveltejs/realworld#41]
Firing up this project with `sapper dev` and then opening the page creates a session. However, on each page refresh a new session file is created:

<img width="626" alt="Screenshot 2019-10-12 at 12 07 45" src="https://user-images.githubusercontent.com/216566/66699641-ee887980-ece8-11e9-8097-b35ec1ffb21d.png">

Also keeps the app logged out most of the time

**Comment by QuantumInformation** [comment]
So my computer has been running a few hours now and I haven't been using the app, there is now around 500 files or so now. Are sessions behaving for anyone else?

**Comment by anudeepreddy** [comment]
Hey @QuantumInformation , I was trying to explore sessions in sapper this morning and ended up with the same issue as yours and after a lot of struggle to understand what was wrong, I figured out that this happens when the browser cache is disabled.

Hope this helps

**Comment by QuantumInformation** [comment]
Hey @anudeepreddy that didn't help me in that case. Are you sure it fixes it for you?

**Comment by anudeepreddy** [comment]
Hey @QuantumInformation , i will explore more and get back to you if i find anything. Enabling cache in dev tools fixed the issue for me

**Comment by Chriscxa** [comment]
Any solution? Think, enabling cache is not an option ;)

**Comment by QuantumInformation** [comment]
Can you try some different versions of sapper?

**Comment by Chriscxa** [comment]
Found out: after every manual pagereload the manifest.json has the new cookie. 
Sapper 0.27.8 is used.
I update sapper 0.27.9 and check again.

**Comment by QuantumInformation** [comment]
manifest.json ?

**Comment by Chriscxa** [comment]
jep. In static folder in this project. I delete it and rebuild again and look what happens.

**Comment by Chriscxa** [comment]
Jep. It was the manifest.json file. File can be found in "static"-folder.  Also remove the link in <head> in template.html where the file is linked.
Thats all.  ;)

**Comment by Chriscxa** [comment]
Issue can be closed

**Comment by rosslh** [comment]
Perhaps try setting `saveUninitialized: false` in your session cookie configuration

**Comment by benmccann** [comment]
A more actively maintained version now lives at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev
