### ISSUE TITLE
prevent requests 

### ISSUE THREAD

**Issue by Chriscxa** [sveltejs/realworld#43]
Hi,

i´m new in svelte and also in JS !!!
I know a feature is that svelte load data in background if user hover over a link. 
Thats really fast if there is a user CLICK that link. But:
If i hover over link/article one = request article one,
Hover over link/article two = request article two.
Back to hover over link one = request again article on 
and so on, so on,  so on.

Can we store the data and compare it with the next hover before fire an request?
Hope you understand me and my bad english :P
Is this a bad solution? Is there a better way?

Thanks for help.

**Comment by QuantumInformation** [comment]
On subsequent hover on the same link the data isn't retrieved. I'm not sure if there is a way to reload in case the server could return a different result.

**Comment by Conduitry** [comment]
Sapper leaves this decision up to you by letting you specify cache-control headers on the endpoint that the prefetch requests. To prevent the endpoint from being requested again, make sure you tell the browser how long it can cache the response.
