### ISSUE TITLE
desynchronized user data?

### ISSUE THREAD

**Issue by brucou** [sveltejs/realworld#44]
I have encountered ond possible issue with the [svelte](https://svelte-realworld.now.sh/) implementation of the Conduit app. After logging in with user brico, then logging out through setting pagei:

- The https://svelte-realworld.now.sh/@bricoi and https://svelte-realworld.now.sh/editor links return a 404. 
-Settings and Home page display the pages as if I would still be logged in.

Could also be a caching problem on my computer?

**Comment by QuantumInformation** [comment]
Duplicate of previous issues.

We are working on a way to get Cloud Run to work nicely.

**Comment by brucou** [comment]
Yeah I saw this one as possibly similar: https://github.com/sveltejs/realworld/issues/26

Alright so closing this
