### ISSUE TITLE
Does Sapper Realworld app is expecting a jwt-token or cookie from the actual server?

### ISSUE THREAD

**Issue by mylastore** [sveltejs/realworld#47]
Does Sapper realworld app is expecting a jwt-token or cookie from the actual server?

**Comment by 3daddict** [comment]
@mylastore I think it expects the jwt. This video helped me in setting up the realworld app for my API: https://www.youtube.com/watch?v=E47uUYvlhQc

**Comment by mylastore** [comment]
> @mylastore I think it expects the jwt. This video helped me in setting up the realworld app for my API: https://www.youtube.com/watch?v=E47uUYvlhQc

is a cookie on that implementation.

**Comment by 3daddict** [comment]
> > @mylastore I think it expects the jwt. This video helped me in setting up the realworld app for my API: https://www.youtube.com/watch?v=E47uUYvlhQc
> 
> is a cookie on that implementation.

The api.js is setup to pass a token in the opts.headers for the requests
The video helped me understand the server setup and how to pass objects thru the middleware

**Comment by Conduitry** [comment]
In the Sapper app, there is a cookie saved with session information. The session contains a token that is retrieved from the remove conduit/realworld servers, and which is sent in an HTTP header during subsequent requests.

**Comment by nltesown** [comment]
> In the Sapper app, there is a cookie saved with session information. The session contains a token that is retrieved from the remove conduit/realworld servers, and which is sent in an HTTP header during subsequent requests.

I'm struggling to see exactly how this happens.

When a user logs in, the `user` object returned from the API is written to the session store (Svelte store). But how is this object passed to the server on subsequent requests?

In [server.js](https://github.com/sveltejs/realworld/blob/e648275b99654749bd7fb785dbaae7f35c47b281/src/server.js#L31
), there is the `sapper.middleware` part which apparently reads the session object on each request. Is this object read from the store? If so, how is it passed concretely?

**Comment by nltesown** [comment]
> In the Sapper app, there is a cookie saved with session information.

I'm struggling to see exactly how this happens.

In server.js:

```js
sapper.middleware({
  session: req => ({
	  user: req.session && req.session.user
	})
})
```

What is `req.session`? Is it read from a cookie? Is this cookie automatically set to the value of the session store (on the client).

What if I refresh the page and lose the session store. Is it automatically populated back with the session passed from the session on the server?
