### ISSUE TITLE
Immature Spam

### ISSUE THREAD

**Issue by robots4life** [sveltejs/realworld#57]
Checked the RealWorld app and found [this](https://realworld.svelte.dev/profile/@sidahitler) person posting quite a lot of junk while also having an adult profile pic. Since I :heart: Svelte and Sapper I am just sending you a heads-up about this. It is just a pity to see this kind of content, but hey, people will be people, I'd get rid of that content and the 2 tags `SIDA` and `HIT..`, thank you.

**Comment by Conduitry** [comment]
This is an unfortunate side-effect of using the realworld app for a frontend framework. They all share the same backend and the same data (see e.g. https://vue-vuex-realworld.netlify.app/#/@sidahitler/) and we don't have any special administrative powers over the content.

**Comment by robots4life** [comment]
Ach.. people will be people, yeah I do get you, no worries, I thought something could be done about it. :+1:
