### ISSUE TITLE
Session does not perssists after refresh

### ISSUE THREAD

**Issue by codewithpatelo** [sveltejs/realworld#61]
I noticed that this code does not prevent sessions to be lost after a page refresh. Should it work that way?

**Comment by capripio** [comment]
@codewithpatelo, use express-session and store session. it will keep session!

**Comment by n1ghtie** [comment]
Any chance you can point in the right direction? I seem to struggle to find a working solution

**Comment by nousacademy** [comment]
The "user" object gets nested on page refresh, its there it just gets undefined due to nesting. In your " login/index.svelte " change lines 26 - 29 to be `		if (response.token) {
			$session.user = response;
			goto('/');
		}` and in " auth/login.js " change the user object to be `		if (response.user) req.session.user = {"id": 1234, "email": "dvdv@ofo.com", "username": "test", "token": "tesssttttt", "bio":null, "image": null}`

**Comment by benmccann** [comment]
A more actively maintained version now lives at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev

**Comment by bcodus** [comment]
> A more actively maintained version now lives at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev

Gives 404

**Comment by benmccann** [comment]
The realworld team would not list projects in a monorepo, so we moved it back here

**Comment by Rich-Harris** [comment]
closing as out of date
