### ISSUE TITLE
Completely missing error handling, progress indicators

### ISSUE THREAD

**Issue by tv42** [sveltejs/realworld#62]
I was hoping to see a "real world" example of both busy indicators (on e.g. form submit) and error handling. It seems this project has placeholders for errors -- never populated -- and no accommodation for any progress/busy indicator. It'd be great to see an actual, complex, example.

**Comment by quantuminformation** [comment]
Check out this https://github.com/quantuminformation/svelte-firebase-starter

**Comment by benmccann** [comment]
A more actively maintained version now lives at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev

**Comment by tv42** [comment]
That sveltekit example seems to have been removed again.

**Comment by benmccann** [comment]
The example was moved back to this repo because the realworld team disallowed any projects that were sub-projects in monorepos from being listed
