### ISSUE TITLE
Sapper export version does not redirect user to login page when not logged in.

### ISSUE THREAD

**Issue by kane81** [sveltejs/realworld#68]
Downloaded the master of realworld sveltejs and ran npm install in VSCode.

Running **npm run dev**  - If I am NOT signed in and hit the url \settings I get redirected to the login screen 👍 

I export out **npx sapper export --legacy**
I run **npx serve __sapper__/export**
- If I am NOT signed in and hit the url \settings I get a 404 instead of being redirected to the login page 👎 

I tried **npx sapper export --legacy --entry '/ settings'**
but still the same 404 error :(

I noticed **realworld.svelte.dev** does  redirected to the login page when hitting \settings and not logged in....

What am I doing wrong with the sapper export / how can I fix this problem so it redirects to the login page?
Do special build instruction need to be included in this project?

Thank you 

Attached is console output

[console-output.txt](https://github.com/sveltejs/realworld/files/5448916/console-output.txt)
![2020-10-27_13-37-10](https://user-images.githubusercontent.com/4944744/97378608-a7305380-1912-11eb-93c7-117f0c6e44b0.jpg)

**Comment by antony** [comment]
The realworld application is not designed to be exported, since that makes a statically generated app which will not support authentication (since it only renders at build time). It needs a node server which you will get with `npm run dev` and `npm run build`

**Comment by kane81** [comment]
Thank you!
