### ISSUE TITLE
Page with preload with undefined variables on refresh

### ISSUE THREAD

**Issue by lsabi** [sveltejs/realworld#72]
Navigating to an article shows it. Let's take as example [https://realworld.svelte.dev/article/dsf-hc9q8m](https://realworld.svelte.dev/article/dsf-hc9q8m).

Then, pressing `F5` to refresh the page, refreshes it and the post remains. When I do the same on a web app I create for trial, the variable `article` is `undefined`.

The issue raises from the fact that the file [https://github.com/sveltejs/realworld/blob/master/src/routes/article/%5Bslug%5D.svelte](https://github.com/sveltejs/realworld/blob/master/src/routes/article/%5Bslug%5D.svelte) contains a preload with (almost) the same code as the one I have (I changed the names and the link), but in my web app it seems to not work.

Is it a problem of my project or the demo is running on a different codebase from the one in the repo?

Thanks.

**Comment by benmccann** [comment]
A more actively maintained version now lives at https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev
