### ISSUE TITLE
Adding SASS PreProcess support

### ISSUE THREAD

**Issue by justindasilva** [sveltejs/realworld#8]
How would I go about adding SASS Preprocessing support to this application?

I have a SO post about it: https://stackoverflow.com/questions/49266016/sapper-svelte-sass-preprocessing

**Comment by MaxMilton** [comment]
Your question is not specific to this repo so general questions are better asked at <https://stackoverflow.com/questions/tagged/svelte>.

That said, a common way to add SASS/SCSS to Svelte components is via [`svelte.preprocess`](https://github.com/sveltejs/svelte#preprocessor-options) — although most of the time you would do it via [svelte-loader](https://github.com/sveltejs/svelte-loader) options or [rollup-plugin-svelte](https://github.com/rollup/rollup-plugin-svelte) options, etc. There are packages which utilize this like <https://github.com/kazzkiq/svelte-preprocess-scss> for SCSS/SASS or <https://github.com/kaisermann/svelte-preprocess> which is more generic and has support for multiple style preprocessors.

For extra reference if you want to write your own Svelte preprocessor, I've made <https://github.com/WeAreGenki/minna-ui/tree/master/utils/svelte-preprocess-style> to run styles through PostCSS plugins and <https://github.com/WeAreGenki/minna-ui/tree/master/utils/svelte-preprocess-markup> to optimise your HTML templates before they hit the Svelte compiler (remove whitespace etc.).
