### ISSUE TITLE
Latest version of svelte-kit doesn't support cjs config

### ISSUE THREAD

**Issue by irshadshalu** [sveltejs/realworld#83]
Since the version specified in `package.json` for sveltekit is `"next"`, It is fetching the latest version of sveltekit which is throwing a lot of errors like 

`svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module.`

Either package.json needs to be updated to use the exact version or the project needs to be updated to conform to the new standards.

**Comment by sayasuhendra** [comment]
change pnpm to npm

```bash
npm install
npm dev
npm build
npm start
```

**Comment by irshadshalu** [comment]
> change pnpm to npm

Have you tried this? I tried this and it wasn't working for me.

**Comment by sayasuhendra** [comment]
sure. it's working for me.

make sure your node version is above 12.
