### ISSUE TITLE
Profile page Error

### ISSUE THREAD

**Issue by benjaminviaud** [sveltejs/realworld#85]
Hello,

When I clone the last version and I go to the profile page it gives an error

500
Unexpected token T in JSON at position 0
SyntaxError: Unexpected token T in JSON at position 0

Index.json.js
```
import * as api from '$lib/api.js';

export async function get({ params, context }) {
	const { profile } = await api.get(`profiles/${params.user}`, context.user && context.user.token);

	return {
		body: profile
	};
}
```

context must be locals

**Comment by benmccann** [comment]
hopefully fixed now
