### ISSUE TITLE
about get({ locals })

### ISSUE THREAD

**Issue by yadoga** [sveltejs/realworld#87]
Quick question about 'locals' in your endpoints:
where are these set? Or are they more of a placeholder for any individual session? Could not seem to find any info about this… thanks!

**Comment by benmccann** [comment]
https://kit.svelte.dev/docs#hooks-handle

**Comment by rvrm** [comment]
works for me now with:

```
export async function handle({ request, render }) {
    const cookies = cookie.parse(request.headers.cookie || '')
    const jwt =
        cookies.jwt && Buffer.from(cookies.jwt, 'base64').toString('utf-8')
    const user = jwt ? JSON.parse(jwt) : null
    request.locals.user = user

    const response = await render(request);

    return response;
}
```

Should [/hooks/index.js](https://github.com/sveltejs/realworld/blob/master/src/hooks/index.js) better not reflect the handle({ request }) method?

Or would handling be possible via the 
```getSession({ headers })``` as in your example and I'm missing something? 
Thank you

**Comment by benmccann** [comment]
I just tested and am not seeing any issues

Here are the docs for `getSession`: https://kit.svelte.dev/docs#hooks-getsession

**Comment by eriknyk** [comment]
however I don't `handle()` setup in the `realworld` example and it is accessing locals.user however `handle()` is not present in hooks definitions `https://github.com/sveltejs/realworld/blob/master/src/hooks/index.js``

**Comment by benmccann** [comment]
Oh yeah. I messed that up. I just pushed a fix in case you want to take another look

**Comment by yadoga** [comment]
Thank you! Link above needs correction, btw.

**Comment by yadoga** [comment]
`headers` keeps returning as 'undefined' for me. My app probably deviates a bit from this repo, but nevertheless leaving the following in case it helps someone:

I'm now getting headers by an async function, via the `request` object.

```
export async function handle({ request, resolve }) {
    const cookies = cookie.parse(request.headers.cookie || '');
    const jwt = cookies.jwt && Buffer.from(cookies.jwt, 'base64').toString('utf-8');
    request.locals.user = jwt ? JSON.parse(jwt) : null;

    const response = await resolve(request);
    return response;
}

```

**Comment by benmccann** [comment]
I just bumped the version of SvelteKit which uses the new method signature for `handle`
