### ISSUE TITLE
Updating this repo with latest version of Sapper

### ISSUE THREAD

**Issue by justindasilva** [sveltejs/realworld#9]
I think it would be nice to update this repo to the latest version of Sapper.

At the same time, showing examples of some of the following would be nice:
- SASS preprocessing in file
- Would be nice to also have examples of how SASS preprocessing with external files would be done. Basically integrating it with the hot module reloader
- I usually use linters for my JS, HTML and SCSS code. Considering all of these are within one file, how would one achieve this?

**Comment by MaxMilton** [comment]
There's no mention of styles preprocessing in the specs so why overcomplicate things?
https://github.com/gothinkster/realworld/tree/master/spec

You can still use linters when using Svelte single file components. Is there something specific you're having a problem with? Not sure if it would be helpful for you but I have a Svelte project with full linting: <https://github.com/WeAreGenki/minna-ui>. You can either run `yarn run lint` or code editor/IDE plugins should automatically pick up the configs and lint components.

**Comment by matt3224** [comment]
Pull request submitted here 
https://github.com/sveltejs/realworld/pull/12

**Comment by pngwn** [comment]
Implemented in #16.
