### ISSUE TITLE
Deprecated getContext - SvelteKit

### ISSUE THREAD

**Issue by gyurielf** [sveltejs/realworld#92]
As far as I know, It is removed from the svelte-kit.
Can you update the examples?

**Comment by Valexr** [comment]
Why it’s removed from svelteKit?

**Comment by gyurielf** [comment]
> Why it’s removed from svelteKit?

https://svelte.dev/blog/whats-new-in-svelte-june-2021

**Comment by Valexr** [comment]
`Removed getContext in favor of request.locals` it’s ok, but why?
